// Environment file generation utilities

import { getPoolConfig, DEFAULT_AUTHORITY_PUBLIC_KEY, DEFAULT_CONFIG_VALUES } from '@/config-templates';

/**
 * Helper function to wrap address in addr(...) format if not already wrapped
 */
const wrapAddressInAddr = (address: string): string => {
  if (!address) return 'addr(bc1q...)';
  // Check if already wrapped
  if (address.startsWith('addr(') && address.endsWith(')')) {
    return address;
  }
  return `addr(${address})`;
};

/**
 * Generate docker_env file content for pool connection deployment
 */
export const generatePoolConnectionEnvFile = (data: any, socketPath?: string): string => {
  const needsSocketPath = !!socketPath;
  const network = (data?.selectedNetwork || "mainnet") as 'mainnet' | 'testnet4';
  const selectedPoolConfig = getPoolConfig(data?.selectedPool, network);
  // Use pool's authority pubkey if available, otherwise default
  const poolAuthorityPubkey = selectedPoolConfig?.authorityPubkey || DEFAULT_AUTHORITY_PUBLIC_KEY;

  let envContent = `# Stratum V2 Pool Connection Environment Variables
# Generated by SRI Deployment Wizard
# Place this file in sv2-apps/docker/docker_env

# Translator Proxy Configuration
TPROXY_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
TPROXY_AGGREGATE_CHANNELS=${selectedPoolConfig?.aggregateChannels ? 'true' : 'false'}
TPROXY_MIN_INDIVIDUAL_MINER_HASHRATE=10_000_000_000_000.0
TPROXY_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
TPROXY_ENABLE_VARDIFF=${needsSocketPath ? 'false' : 'true'}
TPROXY_UPSTREAM_ADDRESS=${needsSocketPath ? '172.28.0.13' : (selectedPoolConfig?.address || '127.0.0.1')}
TPROXY_UPSTREAM_PORT=${needsSocketPath ? DEFAULT_CONFIG_VALUES.jdcPort : (selectedPoolConfig?.port || DEFAULT_CONFIG_VALUES.poolPort)}
TPROXY_UPSTREAM_AUTHORITY_PUBKEY=${data?.tproxyUpstreamAuthorityPubkey || poolAuthorityPubkey}
`;

  if (needsSocketPath) {
    // Use pool's endpoints if available, otherwise fallback to docker IPs for local deployment
    const jdcPoolAddress = selectedPoolConfig?.address || '172.28.0.11';
    const jdcPoolPort = selectedPoolConfig?.port || DEFAULT_CONFIG_VALUES.poolPort;
    const jdcJdsAddress = selectedPoolConfig?.jdsAddress || '172.28.0.12';
    const jdcJdsPort = selectedPoolConfig?.jdsPort || DEFAULT_CONFIG_VALUES.jdsPort;

    envContent += `
# JD Client Configuration (for custom templates)
JDC_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
JDC_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
JDC_SHARE_BATCH_SIZE=${data?.clientShareBatchSize || 10}
JDC_SIGNATURE=${data?.jdcSignature || 'Sv2MinerSignature'}
JDC_COINBASE_REWARD_SCRIPT=${wrapAddressInAddr(data?.coinbaseRewardScript || 'bc1q...')}
JDC_FEE_THRESHOLD=${data?.clientFeeThreshold || 100}
JDC_MIN_INTERVAL=${data?.clientMinInterval || 5}
JDC_UPSTREAM_AUTHORITY_PUBKEY=${poolAuthorityPubkey}
JDC_POOL_ADDRESS=${jdcPoolAddress}
JDC_POOL_PORT=${jdcPoolPort}
JDC_UPSTREAM_JDS_ADDRESS=${jdcJdsAddress}
JDC_UPSTREAM_JDS_PORT=${jdcJdsPort}

# Bitcoin Socket Path
BITCOIN_SOCKET_PATH=${socketPath}
`;
  } else {
    envContent += `
# Bitcoin Socket Path (not needed for tproxy-only, set to /dev/null)
BITCOIN_SOCKET_PATH=/dev/null
`;
  }

  return envContent;
};
