/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * SRI Monitoring API
 * HTTP JSON API for monitoring SV2 applications
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export interface ErrorResponse {
  error: string;
}

export type ExtendedChannelInfoSharesRejectedByReason = {[key: string]: number};

/**
 * Information about an extended channel
 */
export interface ExtendedChannelInfo {
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  expected_shares_per_minute: number;
  extranonce_prefix_hex: string;
  /** @minimum 0 */
  full_extranonce_size: number;
  /** @minimum 0 */
  last_batch_accepted: number;
  /** @minimum 0 */
  last_batch_work_sum: number;
  /** @minimum 0 */
  last_share_sequence_number: number;
  nominal_hashrate: number;
  requested_max_target_hex: string;
  /** @minimum 0 */
  rollable_extranonce_size: number;
  /** @minimum 0 */
  share_batch_size: number;
  share_work_sum: number;
  /** @minimum 0 */
  shares_accepted: number;
  /** @minimum 0 */
  shares_rejected: number;
  shares_rejected_by_reason: ExtendedChannelInfoSharesRejectedByReason;
  stable_hashrate: boolean;
  target_hex: string;
  user_identity: string;
}

/**
 * Aggregate information about the server connection
 */
export interface ServerSummary {
  /** @minimum 0 */
  extended_channels: number;
  /** @minimum 0 */
  standard_channels: number;
  /** @minimum 0 */
  total_channels: number;
  total_hashrate: number;
}

/**
 * Aggregate information about SV1 client connections
 */
export interface Sv1ClientsSummary {
  /** @minimum 0 */
  total_clients: number;
  total_hashrate: number;
}

/**
 * Aggregate information about all Sv2 clients
 */
export interface Sv2ClientsSummary {
  /** @minimum 0 */
  extended_channels: number;
  /** @minimum 0 */
  standard_channels: number;
  /** @minimum 0 */
  total_channels: number;
  /** @minimum 0 */
  total_clients: number;
  total_hashrate: number;
}

/**
 * Global statistics from `/api/v1/global` endpoint
 *
 * Fields are `Option` to distinguish "not monitored" (`None`) from "monitored but empty" (`Some`
 * with zeros).
 *
 * Typical configurations:
 * - **Pool/JDC**: `server` and `sv2_clients` are `Some`, `sv1_clients` is `None`
 * - **tProxy**: `server` and `sv1_clients` are `Some`, `sv2_clients` is `None`
 */
export interface GlobalInfo {
  server?: null | ServerSummary;
  sv1_clients?: null | Sv1ClientsSummary;
  sv2_clients?: null | Sv2ClientsSummary;
  /**
     * Uptime in seconds since the application started
     * @minimum 0
     */
  uptime_secs: number;
}

export interface HealthResponse {
  status: string;
  /** @minimum 0 */
  timestamp: number;
}

export type ServerExtendedChannelInfoSharesRejectedByReason = {[key: string]: number};

/**
 * Information about an extended channel opened with the server
 */
export interface ServerExtendedChannelInfo {
  /**
     * Work acknowledged by upstream via `SubmitSharesSuccess.new_shares_sum`.
     * @minimum 0
     */
  acknowledged_work_sum: number;
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  extranonce_prefix_hex: string;
  /** @minimum 0 */
  full_extranonce_size: number;
  /**
     * None when vardiff is disabled and hashrate cannot be reliably tracked
     * @nullable
     */
  nominal_hashrate?: number | null;
  /** @minimum 0 */
  rollable_extranonce_size: number;
  /** @minimum 0 */
  shares_acknowledged: number;
  /** @minimum 0 */
  shares_rejected: number;
  shares_rejected_by_reason: ServerExtendedChannelInfoSharesRejectedByReason;
  /** @minimum 0 */
  shares_submitted: number;
  target_hex: string;
  user_identity: string;
  /** Work locally validated by the client channel. */
  validated_work_sum: number;
  version_rolling: boolean;
}

export type ServerStandardChannelInfoSharesRejectedByReason = {[key: string]: number};

/**
 * Information about a standard channel opened with the server
 */
export interface ServerStandardChannelInfo {
  /**
     * Work acknowledged by upstream via `SubmitSharesSuccess.new_shares_sum`.
     * @minimum 0
     */
  acknowledged_work_sum: number;
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  extranonce_prefix_hex: string;
  /**
     * None when vardiff is disabled and hashrate cannot be reliably tracked
     * @nullable
     */
  nominal_hashrate?: number | null;
  /** @minimum 0 */
  shares_acknowledged: number;
  /** @minimum 0 */
  shares_rejected: number;
  shares_rejected_by_reason: ServerStandardChannelInfoSharesRejectedByReason;
  /** @minimum 0 */
  shares_submitted: number;
  target_hex: string;
  user_identity: string;
  /** Work locally validated by the client channel. */
  validated_work_sum: number;
}

export interface ServerChannelsResponse {
  extended_channels: ServerExtendedChannelInfo[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  standard_channels: ServerStandardChannelInfo[];
  /** @minimum 0 */
  total_extended: number;
  /** @minimum 0 */
  total_standard: number;
}

export interface ServerResponse {
  /** @minimum 0 */
  extended_channels_count: number;
  /** @minimum 0 */
  standard_channels_count: number;
  total_hashrate: number;
}

export type StandardChannelInfoSharesRejectedByReason = {[key: string]: number};

/**
 * Information about a standard channel
 */
export interface StandardChannelInfo {
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  expected_shares_per_minute: number;
  extranonce_prefix_hex: string;
  /** @minimum 0 */
  last_batch_accepted: number;
  /** @minimum 0 */
  last_batch_work_sum: number;
  /** @minimum 0 */
  last_share_sequence_number: number;
  nominal_hashrate: number;
  requested_max_target_hex: string;
  /** @minimum 0 */
  share_batch_size: number;
  share_work_sum: number;
  /** @minimum 0 */
  shares_accepted: number;
  /** @minimum 0 */
  shares_rejected: number;
  shares_rejected_by_reason: StandardChannelInfoSharesRejectedByReason;
  stable_hashrate: boolean;
  target_hex: string;
  user_identity: string;
}

/**
 * Information about a single SV1 client connection
 */
export interface Sv1ClientInfo {
  authorized_worker_name: string;
  /**
     * @minimum 0
     * @nullable
     */
  channel_id?: number | null;
  /** @minimum 0 */
  client_id: number;
  extranonce1_hex: string;
  /** @minimum 0 */
  extranonce2_len: number;
  /** @nullable */
  hashrate?: number | null;
  stable_hashrate: boolean;
  target_hex: string;
  user_identity: string;
  /** @nullable */
  version_rolling_mask?: string | null;
  /** @nullable */
  version_rolling_min_bit?: string | null;
}

export interface Sv1ClientsResponse {
  items: Sv1ClientInfo[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
}

export interface Sv2ClientChannelsResponse {
  /** @minimum 0 */
  client_id: number;
  extended_channels: ExtendedChannelInfo[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  standard_channels: StandardChannelInfo[];
  /** @minimum 0 */
  total_extended: number;
  /** @minimum 0 */
  total_standard: number;
}

/**
 * Full information about a single Sv2 client including all channels
 */
export interface Sv2ClientInfo {
  /** @minimum 0 */
  client_id: number;
  extended_channels: ExtendedChannelInfo[];
  standard_channels: StandardChannelInfo[];
}

/**
 * Sv2 client metadata without channel arrays (for listings)
 */
export interface Sv2ClientMetadata {
  /** @minimum 0 */
  client_id: number;
  /** @minimum 0 */
  extended_channels_count: number;
  /** @minimum 0 */
  standard_channels_count: number;
  total_hashrate: number;
}

export interface Sv2ClientResponse {
  /** @minimum 0 */
  client_id: number;
  /** @minimum 0 */
  extended_channels_count: number;
  /** @minimum 0 */
  standard_channels_count: number;
  total_hashrate: number;
}

export interface Sv2ClientsResponse {
  items: Sv2ClientMetadata[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
}

export type HandleClientsParams = {
/**
 * Offset for pagination (default: 0)
 * @minimum 0
 */
offset?: number;
/**
 * Limit for pagination (default: 25, max: 100)
 * @minimum 0
 * @nullable
 */
limit?: number | null;
};

export type HandleClientChannelsParams = {
/**
 * Offset for pagination (default: 0)
 * @minimum 0
 */
offset?: number;
/**
 * Limit for pagination (default: 25, max: 100)
 * @minimum 0
 * @nullable
 */
limit?: number | null;
};

export type HandleServerChannelsParams = {
/**
 * Offset for pagination (default: 0)
 * @minimum 0
 */
offset?: number;
/**
 * Limit for pagination (default: 25, max: 100)
 * @minimum 0
 * @nullable
 */
limit?: number | null;
};

export type HandleSv1ClientsParams = {
/**
 * Offset for pagination (default: 0)
 * @minimum 0
 */
offset?: number;
/**
 * Limit for pagination (default: 25, max: 100)
 * @minimum 0
 * @nullable
 */
limit?: number | null;
};

export type handleClientsResponse200 = {
  data: Sv2ClientsResponse
  status: 200
}

export type handleClientsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleClientsResponseSuccess = (handleClientsResponse200) & {
  headers: Headers;
};
export type handleClientsResponseError = (handleClientsResponse404) & {
  headers: Headers;
};

export type handleClientsResponse = (handleClientsResponseSuccess | handleClientsResponseError)

export const getHandleClientsUrl = (params?: HandleClientsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/clients?${stringifiedParams}` : `/api/v1/clients`
}

/**
 * @summary Get all Sv2 clients (downstream) - returns metadata only, use /clients/{id}/channels for
channels
 */
export const handleClients = async (params?: HandleClientsParams, options?: RequestInit): Promise<handleClientsResponse> => {

  const res = await fetch(getHandleClientsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleClientsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleClientsResponse
}





export const getHandleClientsQueryKey = (params?: HandleClientsParams,) => {
    return [
    `/api/v1/clients`, ...(params ? [params] : [])
    ] as const;
    }


export const getHandleClientsQueryOptions = <TData = Awaited<ReturnType<typeof handleClients>>, TError = ErrorResponse>(params?: HandleClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClients>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleClientsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleClients>>> = ({ signal }) => handleClients(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleClients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleClientsQueryResult = NonNullable<Awaited<ReturnType<typeof handleClients>>>
export type HandleClientsQueryError = ErrorResponse


export function useHandleClients<TData = Awaited<ReturnType<typeof handleClients>>, TError = ErrorResponse>(
 params: undefined |  HandleClientsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleClients>>,
          TError,
          Awaited<ReturnType<typeof handleClients>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleClients<TData = Awaited<ReturnType<typeof handleClients>>, TError = ErrorResponse>(
 params?: HandleClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleClients>>,
          TError,
          Awaited<ReturnType<typeof handleClients>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleClients<TData = Awaited<ReturnType<typeof handleClients>>, TError = ErrorResponse>(
 params?: HandleClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClients>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Sv2 clients (downstream) - returns metadata only, use /clients/{id}/channels for
channels
 */

export function useHandleClients<TData = Awaited<ReturnType<typeof handleClients>>, TError = ErrorResponse>(
 params?: HandleClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClients>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleClientsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleClientByIdResponse200 = {
  data: Sv2ClientResponse
  status: 200
}

export type handleClientByIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleClientByIdResponseSuccess = (handleClientByIdResponse200) & {
  headers: Headers;
};
export type handleClientByIdResponseError = (handleClientByIdResponse404) & {
  headers: Headers;
};

export type handleClientByIdResponse = (handleClientByIdResponseSuccess | handleClientByIdResponseError)

export const getHandleClientByIdUrl = (clientId: number,) => {




  return `/api/v1/clients/${clientId}`
}

/**
 * @summary Get a single Sv2 client by ID - returns metadata only, use /clients/{id}/channels for channels
 */
export const handleClientById = async (clientId: number, options?: RequestInit): Promise<handleClientByIdResponse> => {

  const res = await fetch(getHandleClientByIdUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleClientByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleClientByIdResponse
}





export const getHandleClientByIdQueryKey = (clientId: number,) => {
    return [
    `/api/v1/clients/${clientId}`
    ] as const;
    }


export const getHandleClientByIdQueryOptions = <TData = Awaited<ReturnType<typeof handleClientById>>, TError = ErrorResponse>(clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientById>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleClientByIdQueryKey(clientId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleClientById>>> = ({ signal }) => handleClientById(clientId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: clientId !== null && clientId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleClientById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleClientByIdQueryResult = NonNullable<Awaited<ReturnType<typeof handleClientById>>>
export type HandleClientByIdQueryError = ErrorResponse


export function useHandleClientById<TData = Awaited<ReturnType<typeof handleClientById>>, TError = ErrorResponse>(
 clientId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleClientById>>,
          TError,
          Awaited<ReturnType<typeof handleClientById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleClientById<TData = Awaited<ReturnType<typeof handleClientById>>, TError = ErrorResponse>(
 clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleClientById>>,
          TError,
          Awaited<ReturnType<typeof handleClientById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleClientById<TData = Awaited<ReturnType<typeof handleClientById>>, TError = ErrorResponse>(
 clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single Sv2 client by ID - returns metadata only, use /clients/{id}/channels for channels
 */

export function useHandleClientById<TData = Awaited<ReturnType<typeof handleClientById>>, TError = ErrorResponse>(
 clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleClientByIdQueryOptions(clientId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleClientChannelsResponse200 = {
  data: Sv2ClientChannelsResponse
  status: 200
}

export type handleClientChannelsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleClientChannelsResponseSuccess = (handleClientChannelsResponse200) & {
  headers: Headers;
};
export type handleClientChannelsResponseError = (handleClientChannelsResponse404) & {
  headers: Headers;
};

export type handleClientChannelsResponse = (handleClientChannelsResponseSuccess | handleClientChannelsResponseError)

export const getHandleClientChannelsUrl = (clientId: number,
    params?: HandleClientChannelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/clients/${clientId}/channels?${stringifiedParams}` : `/api/v1/clients/${clientId}/channels`
}

/**
 * @summary Get channels for a specific Sv2 client (paginated)
 */
export const handleClientChannels = async (clientId: number,
    params?: HandleClientChannelsParams, options?: RequestInit): Promise<handleClientChannelsResponse> => {

  const res = await fetch(getHandleClientChannelsUrl(clientId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleClientChannelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleClientChannelsResponse
}





export const getHandleClientChannelsQueryKey = (clientId: number,
    params?: HandleClientChannelsParams,) => {
    return [
    `/api/v1/clients/${clientId}/channels`, ...(params ? [params] : [])
    ] as const;
    }


export const getHandleClientChannelsQueryOptions = <TData = Awaited<ReturnType<typeof handleClientChannels>>, TError = ErrorResponse>(clientId: number,
    params?: HandleClientChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientChannels>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleClientChannelsQueryKey(clientId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleClientChannels>>> = ({ signal }) => handleClientChannels(clientId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: clientId !== null && clientId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleClientChannels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleClientChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof handleClientChannels>>>
export type HandleClientChannelsQueryError = ErrorResponse


export function useHandleClientChannels<TData = Awaited<ReturnType<typeof handleClientChannels>>, TError = ErrorResponse>(
 clientId: number,
    params: undefined |  HandleClientChannelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientChannels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleClientChannels>>,
          TError,
          Awaited<ReturnType<typeof handleClientChannels>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleClientChannels<TData = Awaited<ReturnType<typeof handleClientChannels>>, TError = ErrorResponse>(
 clientId: number,
    params?: HandleClientChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientChannels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleClientChannels>>,
          TError,
          Awaited<ReturnType<typeof handleClientChannels>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleClientChannels<TData = Awaited<ReturnType<typeof handleClientChannels>>, TError = ErrorResponse>(
 clientId: number,
    params?: HandleClientChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientChannels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get channels for a specific Sv2 client (paginated)
 */

export function useHandleClientChannels<TData = Awaited<ReturnType<typeof handleClientChannels>>, TError = ErrorResponse>(
 clientId: number,
    params?: HandleClientChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleClientChannels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleClientChannelsQueryOptions(clientId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleGlobalResponse200 = {
  data: GlobalInfo
  status: 200
}

export type handleGlobalResponseSuccess = (handleGlobalResponse200) & {
  headers: Headers;
};
;

export type handleGlobalResponse = (handleGlobalResponseSuccess)

export const getHandleGlobalUrl = () => {




  return `/api/v1/global`
}

/**
 * Returns aggregated statistics for the server (upstream) and clients (downstream).
 * Fields are omitted from the response if that type of monitoring is not enabled.
 *
 * **Typical responses:**
 * - **Pool/JDC**: `server` + `clients` (Sv2 downstream)
 * - **tProxy**: `server` + `sv1_clients` (Sv1 miners)
 * @summary Get global statistics
 */
export const handleGlobal = async ( options?: RequestInit): Promise<handleGlobalResponse> => {

  const res = await fetch(getHandleGlobalUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleGlobalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleGlobalResponse
}





export const getHandleGlobalQueryKey = () => {
    return [
    `/api/v1/global`
    ] as const;
    }


export const getHandleGlobalQueryOptions = <TData = Awaited<ReturnType<typeof handleGlobal>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGlobal>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleGlobalQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleGlobal>>> = ({ signal }) => handleGlobal({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleGlobal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleGlobalQueryResult = NonNullable<Awaited<ReturnType<typeof handleGlobal>>>
export type HandleGlobalQueryError = unknown


export function useHandleGlobal<TData = Awaited<ReturnType<typeof handleGlobal>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGlobal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleGlobal>>,
          TError,
          Awaited<ReturnType<typeof handleGlobal>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleGlobal<TData = Awaited<ReturnType<typeof handleGlobal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGlobal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleGlobal>>,
          TError,
          Awaited<ReturnType<typeof handleGlobal>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleGlobal<TData = Awaited<ReturnType<typeof handleGlobal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGlobal>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get global statistics
 */

export function useHandleGlobal<TData = Awaited<ReturnType<typeof handleGlobal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGlobal>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleGlobalQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleHealthResponse200 = {
  data: HealthResponse
  status: 200
}

export type handleHealthResponseSuccess = (handleHealthResponse200) & {
  headers: Headers;
};
;

export type handleHealthResponse = (handleHealthResponseSuccess)

export const getHandleHealthUrl = () => {




  return `/api/v1/health`
}

/**
 * @summary Health check endpoint
 */
export const handleHealth = async ( options?: RequestInit): Promise<handleHealthResponse> => {

  const res = await fetch(getHandleHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleHealthResponse
}





export const getHandleHealthQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getHandleHealthQueryOptions = <TData = Awaited<ReturnType<typeof handleHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleHealth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleHealth>>> = ({ signal }) => handleHealth({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleHealthQueryResult = NonNullable<Awaited<ReturnType<typeof handleHealth>>>
export type HandleHealthQueryError = unknown


export function useHandleHealth<TData = Awaited<ReturnType<typeof handleHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleHealth>>,
          TError,
          Awaited<ReturnType<typeof handleHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleHealth<TData = Awaited<ReturnType<typeof handleHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleHealth>>,
          TError,
          Awaited<ReturnType<typeof handleHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleHealth<TData = Awaited<ReturnType<typeof handleHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check endpoint
 */

export function useHandleHealth<TData = Awaited<ReturnType<typeof handleHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleServerResponse200 = {
  data: ServerResponse
  status: 200
}

export type handleServerResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleServerResponseSuccess = (handleServerResponse200) & {
  headers: Headers;
};
export type handleServerResponseError = (handleServerResponse404) & {
  headers: Headers;
};

export type handleServerResponse = (handleServerResponseSuccess | handleServerResponseError)

export const getHandleServerUrl = () => {




  return `/api/v1/server`
}

/**
 * @summary Get server (upstream) metadata - use /server/channels for channel details
 */
export const handleServer = async ( options?: RequestInit): Promise<handleServerResponse> => {

  const res = await fetch(getHandleServerUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleServerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleServerResponse
}





export const getHandleServerQueryKey = () => {
    return [
    `/api/v1/server`
    ] as const;
    }


export const getHandleServerQueryOptions = <TData = Awaited<ReturnType<typeof handleServer>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServer>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleServerQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleServer>>> = ({ signal }) => handleServer({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleServer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleServerQueryResult = NonNullable<Awaited<ReturnType<typeof handleServer>>>
export type HandleServerQueryError = ErrorResponse


export function useHandleServer<TData = Awaited<ReturnType<typeof handleServer>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleServer>>,
          TError,
          Awaited<ReturnType<typeof handleServer>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleServer<TData = Awaited<ReturnType<typeof handleServer>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleServer>>,
          TError,
          Awaited<ReturnType<typeof handleServer>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleServer<TData = Awaited<ReturnType<typeof handleServer>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServer>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get server (upstream) metadata - use /server/channels for channel details
 */

export function useHandleServer<TData = Awaited<ReturnType<typeof handleServer>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServer>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleServerQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleServerChannelsResponse200 = {
  data: ServerChannelsResponse
  status: 200
}

export type handleServerChannelsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleServerChannelsResponseSuccess = (handleServerChannelsResponse200) & {
  headers: Headers;
};
export type handleServerChannelsResponseError = (handleServerChannelsResponse404) & {
  headers: Headers;
};

export type handleServerChannelsResponse = (handleServerChannelsResponseSuccess | handleServerChannelsResponseError)

export const getHandleServerChannelsUrl = (params?: HandleServerChannelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/server/channels?${stringifiedParams}` : `/api/v1/server/channels`
}

/**
 * @summary Get server channels (paginated)
 */
export const handleServerChannels = async (params?: HandleServerChannelsParams, options?: RequestInit): Promise<handleServerChannelsResponse> => {

  const res = await fetch(getHandleServerChannelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleServerChannelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleServerChannelsResponse
}





export const getHandleServerChannelsQueryKey = (params?: HandleServerChannelsParams,) => {
    return [
    `/api/v1/server/channels`, ...(params ? [params] : [])
    ] as const;
    }


export const getHandleServerChannelsQueryOptions = <TData = Awaited<ReturnType<typeof handleServerChannels>>, TError = ErrorResponse>(params?: HandleServerChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServerChannels>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleServerChannelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleServerChannels>>> = ({ signal }) => handleServerChannels(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleServerChannels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleServerChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof handleServerChannels>>>
export type HandleServerChannelsQueryError = ErrorResponse


export function useHandleServerChannels<TData = Awaited<ReturnType<typeof handleServerChannels>>, TError = ErrorResponse>(
 params: undefined |  HandleServerChannelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServerChannels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleServerChannels>>,
          TError,
          Awaited<ReturnType<typeof handleServerChannels>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleServerChannels<TData = Awaited<ReturnType<typeof handleServerChannels>>, TError = ErrorResponse>(
 params?: HandleServerChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServerChannels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleServerChannels>>,
          TError,
          Awaited<ReturnType<typeof handleServerChannels>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleServerChannels<TData = Awaited<ReturnType<typeof handleServerChannels>>, TError = ErrorResponse>(
 params?: HandleServerChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServerChannels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get server channels (paginated)
 */

export function useHandleServerChannels<TData = Awaited<ReturnType<typeof handleServerChannels>>, TError = ErrorResponse>(
 params?: HandleServerChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleServerChannels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleServerChannelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleSv1ClientsResponse200 = {
  data: Sv1ClientsResponse
  status: 200
}

export type handleSv1ClientsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleSv1ClientsResponseSuccess = (handleSv1ClientsResponse200) & {
  headers: Headers;
};
export type handleSv1ClientsResponseError = (handleSv1ClientsResponse404) & {
  headers: Headers;
};

export type handleSv1ClientsResponse = (handleSv1ClientsResponseSuccess | handleSv1ClientsResponseError)

export const getHandleSv1ClientsUrl = (params?: HandleSv1ClientsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sv1/clients?${stringifiedParams}` : `/api/v1/sv1/clients`
}

/**
 * @summary Get Sv1 clients (Translator Proxy only)
 */
export const handleSv1Clients = async (params?: HandleSv1ClientsParams, options?: RequestInit): Promise<handleSv1ClientsResponse> => {

  const res = await fetch(getHandleSv1ClientsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleSv1ClientsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleSv1ClientsResponse
}





export const getHandleSv1ClientsQueryKey = (params?: HandleSv1ClientsParams,) => {
    return [
    `/api/v1/sv1/clients`, ...(params ? [params] : [])
    ] as const;
    }


export const getHandleSv1ClientsQueryOptions = <TData = Awaited<ReturnType<typeof handleSv1Clients>>, TError = ErrorResponse>(params?: HandleSv1ClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1Clients>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleSv1ClientsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleSv1Clients>>> = ({ signal }) => handleSv1Clients(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleSv1Clients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleSv1ClientsQueryResult = NonNullable<Awaited<ReturnType<typeof handleSv1Clients>>>
export type HandleSv1ClientsQueryError = ErrorResponse


export function useHandleSv1Clients<TData = Awaited<ReturnType<typeof handleSv1Clients>>, TError = ErrorResponse>(
 params: undefined |  HandleSv1ClientsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1Clients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleSv1Clients>>,
          TError,
          Awaited<ReturnType<typeof handleSv1Clients>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleSv1Clients<TData = Awaited<ReturnType<typeof handleSv1Clients>>, TError = ErrorResponse>(
 params?: HandleSv1ClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1Clients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleSv1Clients>>,
          TError,
          Awaited<ReturnType<typeof handleSv1Clients>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleSv1Clients<TData = Awaited<ReturnType<typeof handleSv1Clients>>, TError = ErrorResponse>(
 params?: HandleSv1ClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1Clients>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Sv1 clients (Translator Proxy only)
 */

export function useHandleSv1Clients<TData = Awaited<ReturnType<typeof handleSv1Clients>>, TError = ErrorResponse>(
 params?: HandleSv1ClientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1Clients>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleSv1ClientsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type handleSv1ClientByIdResponse200 = {
  data: Sv1ClientInfo
  status: 200
}

export type handleSv1ClientByIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type handleSv1ClientByIdResponseSuccess = (handleSv1ClientByIdResponse200) & {
  headers: Headers;
};
export type handleSv1ClientByIdResponseError = (handleSv1ClientByIdResponse404) & {
  headers: Headers;
};

export type handleSv1ClientByIdResponse = (handleSv1ClientByIdResponseSuccess | handleSv1ClientByIdResponseError)

export const getHandleSv1ClientByIdUrl = (clientId: number,) => {




  return `/api/v1/sv1/clients/${clientId}`
}

/**
 * @summary Get a single Sv1 client by ID
 */
export const handleSv1ClientById = async (clientId: number, options?: RequestInit): Promise<handleSv1ClientByIdResponse> => {

  const res = await fetch(getHandleSv1ClientByIdUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: handleSv1ClientByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleSv1ClientByIdResponse
}





export const getHandleSv1ClientByIdQueryKey = (clientId: number,) => {
    return [
    `/api/v1/sv1/clients/${clientId}`
    ] as const;
    }


export const getHandleSv1ClientByIdQueryOptions = <TData = Awaited<ReturnType<typeof handleSv1ClientById>>, TError = ErrorResponse>(clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1ClientById>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleSv1ClientByIdQueryKey(clientId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleSv1ClientById>>> = ({ signal }) => handleSv1ClientById(clientId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: clientId !== null && clientId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleSv1ClientById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleSv1ClientByIdQueryResult = NonNullable<Awaited<ReturnType<typeof handleSv1ClientById>>>
export type HandleSv1ClientByIdQueryError = ErrorResponse


export function useHandleSv1ClientById<TData = Awaited<ReturnType<typeof handleSv1ClientById>>, TError = ErrorResponse>(
 clientId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1ClientById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleSv1ClientById>>,
          TError,
          Awaited<ReturnType<typeof handleSv1ClientById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleSv1ClientById<TData = Awaited<ReturnType<typeof handleSv1ClientById>>, TError = ErrorResponse>(
 clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1ClientById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleSv1ClientById>>,
          TError,
          Awaited<ReturnType<typeof handleSv1ClientById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleSv1ClientById<TData = Awaited<ReturnType<typeof handleSv1ClientById>>, TError = ErrorResponse>(
 clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1ClientById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single Sv1 client by ID
 */

export function useHandleSv1ClientById<TData = Awaited<ReturnType<typeof handleSv1ClientById>>, TError = ErrorResponse>(
 clientId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleSv1ClientById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleSv1ClientByIdQueryOptions(clientId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
