/**
 * Generate TOML configuration files for JDC and Translator
 * Based on sv2-apps/docker/config templates
 */

import type { SetupData } from './types.js';

/**
 * Generate Translator Proxy config (tproxy-config.toml)
 */
export function generateTranslatorConfig(data: SetupData): string {
  const { pool, translator, mode } = data;
  
  // If JD mode, translator connects to JDC container; otherwise directly to pool
  // Both containers are on sv2-network, so we can use the container name as hostname
  // (hostname resolution supported since sv2-apps PR #286)
  const upstreamAddress = mode === 'jd' ? 'sv2-jdc' : pool.address;
  const upstreamPort = mode === 'jd' ? 34265 : pool.port;
  // When connecting to local JDC, we don't need authority key (using hardcoded keys)
  // When connecting to external pool, we need the pool's authority key
  const authorityPubkey = mode === 'jd' 
    ? '9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72'
    : pool.authority_public_key;

  // Min hashrate from user config (default 100 TH/s if not set)
  const minHashrate = translator.min_hashrate ? `${translator.min_hashrate}.0` : '100_000_000_000_000.0';
  // Shares per minute target
  const sharesPerMinute = '6.0';

  return `# Translator Proxy Configuration
# Generated by sv2-ui

# Local Mining Device Downstream Connection
downstream_address = "0.0.0.0"
downstream_port = 34255

# Version support
max_supported_version = 2
min_supported_version = 2

# Extranonce2 size for downstream connections
downstream_extranonce2_size = 4

# User identity/username for pool connection
user_identity = "${translator.user_identity}"

# Aggregate channels: if true, all miners share one upstream channel
aggregate_channels = ${translator.aggregate_channels}

# Protocol extensions configuration
supported_extensions = []
required_extensions = []

# Monitoring HTTP server address
monitoring_address = "0.0.0.0:9092"
monitoring_cache_refresh_secs = 15

# Difficulty params
[downstream_difficulty_config]
min_individual_miner_hashrate = ${minHashrate}
shares_per_minute = ${sharesPerMinute}
enable_vardiff = true
job_keepalive_interval_secs = 60

[[upstreams]]
address = "${upstreamAddress}"
port = ${upstreamPort}
authority_pubkey = "${authorityPubkey}"
`;
}

/**
 * Generate JD Client config (jdc-config.toml)
 */
export function generateJdcConfig(data: SetupData): string | null {
  if (data.mode !== 'jd' || !data.jdc || !data.bitcoin) {
    return null;
  }

  const { pool, jdc, bitcoin } = data;

  // Shares per minute and batch size
  const sharesPerMinute = '6.0';
  const shareBatchSize = '5';
  // Fee threshold and min interval for template provider
  const feeThreshold = '1000';
  const minInterval = '1';

  return `# JD Client Configuration
# Generated by sv2-ui

listening_address = "0.0.0.0:34265"

# Version support
max_supported_version = 2
min_supported_version = 2

# Auth keys for downstream connections
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

# User identity/username for pool connection
user_identity = "${jdc.user_identity}"

# Shares configuration
shares_per_minute = ${sharesPerMinute}
share_batch_size = ${shareBatchSize}

# JDC mode: FULLTEMPLATE or COINBASEONLY
mode = "FULLTEMPLATE"

# String to be added into the Coinbase scriptSig
jdc_signature = "${jdc.jdc_signature}"

# Solo Mining config - coinbase output for fallback solo mining
coinbase_reward_script = "addr(${jdc.coinbase_reward_address})"

# Protocol Extensions
supported_extensions = []
required_extensions = []

# Monitoring HTTP server address
monitoring_address = "0.0.0.0:9091"
monitoring_cache_refresh_secs = 15

# Upstream pool connection
[[upstreams]]
authority_pubkey = "${pool.authority_public_key}"
pool_address = "${pool.address}"
pool_port = ${pool.port}
jds_address = "${pool.address}"
jds_port = 3334

# Bitcoin Core IPC config
[template_provider_type.BitcoinCoreIpc]
network = "${bitcoin.network}"
fee_threshold = ${feeThreshold}
min_interval = ${minInterval}
`;
}
