/**
 * Validate that the TOML generated by this branch is accepted by the sv2-apps
 * images selected by this branch. Release branches therefore validate their
 * pinned sv2-apps tags before sv2-ui is published.
 *
 * This is intentionally not a mining integration test. The services may exit
 * after loading config because their real runtime dependencies are absent; that
 * is acceptable as long as they did not fail while reading/parsing config.
 */

import { randomUUID } from 'node:crypto';
import { execFile, spawn } from 'node:child_process';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { JDC_AUTHORITY_PUBLIC_KEY, SV2_APP_IMAGES } from '@sv2-ui/shared';
import { prepareServiceConfig } from './service-config.js';
import type { SetupData } from './types.js';

const execFileAsync = promisify(execFile);
const CONFIG_ACCEPTANCE_WINDOW_MS = 2_500;
// Head and tail of the container output retained for diagnostics (about
// 1 MiB combined). The middle of longer streams is drained and discarded so
// a noisy container cannot grow this process' heap without bound.
const MAX_RETAINED_OUTPUT_LENGTH = 512 * 1024;
const OUTPUT_TRUNCATION_NOTICE = '\n[sv2-ui compatibility check dropped the middle of this output]\n';
const TEST_POOL_PORT = 34254;
const MALFORMED_CONFIG = 'invalid = [\n';

const CONFIG_ERROR_PATTERNS = [
  /failed to (read|load|parse).*config/i,
  /config.*(error|invalid|missing|parse|deserialize)/i,
  /tomlerror/i,
  /toml.*(error|parse|deserialize)/i,
  /deserialize/i,
  /missing field/i,
  /unknown field/i,
  /unknown variant/i,
  /invalid type/i,
  /invalid value/i,
];

const DOCKER_ERROR_PATTERNS = [
  /docker API/i,
  /docker daemon/i,
  /permission denied.*docker/i,
  /cannot connect to the docker/i,
];

/**
 * Await a promise, falling back to null after ms. The fallback timer is
 * cleared as soon as the race settles, so a timer that loses the race cannot
 * keep this process' event loop alive after main() finishes.
 */
async function raceWithTimeout<T>(promise: Promise<T>, ms: number): Promise<T | null> {
  let timer: NodeJS.Timeout | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<null>((resolve) => {
        timer = setTimeout(() => resolve(null), ms);
      }),
    ]);
  } finally {
    if (timer !== undefined) {
      clearTimeout(timer);
    }
  }
}

function hasConfigError(output: string): boolean {
  return CONFIG_ERROR_PATTERNS.some((pattern) => pattern.test(output));
}

function hasDockerError(output: string): boolean {
  return DOCKER_ERROR_PATTERNS.some((pattern) => pattern.test(output));
}

type BoundedOutputCapture = {
  append: (chunk: Buffer) => void;
  text: () => string;
};

/**
 * Collect a child process' output while keeping only its first and last
 * MAX_RETAINED_OUTPUT_LENGTH characters. Config errors are expected near the
 * start of the stream (parse failure) or near its end (late error before
 * shutdown), so dropping the middle keeps the diagnostics usable while
 * bounding memory even when a container streams output without stopping.
 */
function createBoundedOutputCapture(): BoundedOutputCapture {
  let head = '';
  let tail = '';
  let droppedCharacters = 0;

  return {
    append: (chunk: Buffer): void => {
      tail += chunk.toString();
      if (tail.length <= MAX_RETAINED_OUTPUT_LENGTH) {
        return;
      }

      const overflow = tail.length - MAX_RETAINED_OUTPUT_LENGTH;
      const retained = Math.min(overflow, MAX_RETAINED_OUTPUT_LENGTH - head.length);
      head += tail.slice(0, retained);
      droppedCharacters += overflow - retained;
      tail = tail.slice(overflow);
    },
    text: (): string => {
      if (droppedCharacters === 0) {
        return head + tail;
      }

      return head + OUTPUT_TRUNCATION_NOTICE + tail;
    },
  };
}

async function checkGeneratedConfig(
  label: string,
  image: string,
  configPath: string,
  servicePath: string,
  serviceBinary: string,
): Promise<void> {
  const result = await runConfigCommand(
    label,
    image,
    configPath,
    servicePath,
    serviceBinary,
  );

  if (result.kind === 'still-running') {
    console.log(`${label} stayed up long enough to accept the generated config.`);
    return;
  }

  if (hasDockerError(result.output)) {
    throw new Error(`Docker could not run ${label}.\n${result.output}`);
  }

  if (hasConfigError(result.output)) {
    throw new Error(`${label} rejected the generated config (code ${result.code}, signal ${result.signal}).\n${result.output}`);
  }

  console.log(`${label} loaded config, then exited because runtime dependencies are not present.`);
}

async function assertConfigErrorsAreRecognized(
  label: string,
  image: string,
  configPath: string,
  servicePath: string,
  serviceBinary: string,
): Promise<void> {
  const result = await runConfigCommand(
    `${label} malformed-config canary`,
    image,
    configPath,
    servicePath,
    serviceBinary,
  );

  if (result.kind === 'still-running' || !hasConfigError(result.output)) {
    if (result.kind === 'exited' && hasDockerError(result.output)) {
      throw new Error(`Docker could not run ${label} malformed-config canary.\n${result.output}`);
    }

    throw new Error(
      `Could not recognize ${label} config error output. Update this compatibility check before trusting it.\n${result.kind === 'exited' ? result.output : ''}`,
    );
  }
}

async function pullImage(image: string): Promise<void> {
  console.log(`Pulling ${image}`);
  await execFileAsync('docker', ['pull', image], { maxBuffer: 10 * 1024 * 1024 });
}

async function runConfigCommand(
  label: string,
  image: string,
  configPath: string,
  servicePath: string,
  serviceBinary: string,
): Promise<
  | { kind: 'still-running'; output: string }
  | { kind: 'exited'; code: number | null; signal: NodeJS.Signals | null; output: string }
> {
  console.log(`Checking ${label} with ${image}`);

  const name = `sv2-ui-config-check-${randomUUID()}`;
  const args = [
    'run', '--rm', '--name', name, '--network', 'none',
    '-v', `${configPath}:${servicePath}:ro`,
    '--entrypoint', serviceBinary,
    image,
    '-c', servicePath,
  ];
  const child = spawn('docker', args, { stdio: ['ignore', 'pipe', 'pipe'] });
  const output = createBoundedOutputCapture();
  child.stdout.on('data', (chunk: Buffer) => { output.append(chunk); });
  child.stderr.on('data', (chunk: Buffer) => { output.append(chunk); });

  const exited = new Promise<{ code: number | null; signal: NodeJS.Signals | null }>((resolve, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) => resolve({ code, signal }));
  });

  try {
    const result = await raceWithTimeout(exited, CONFIG_ACCEPTANCE_WINDOW_MS);

    if (!result) {
      return { kind: 'still-running', output: output.text() };
    }

    return { kind: 'exited', code: result.code, signal: result.signal, output: output.text() };
  } finally {
    if (!child.killed) {
      await execFileAsync('docker', ['kill', name]).catch(() => undefined);
      child.kill('SIGINT');
    }
    await raceWithTimeout(exited, 10_000);
    await execFileAsync('docker', ['rm', '--force', name]).catch(() => undefined);
  }
}

function baseSetup(): SetupData {
  return {
    miningMode: 'pool',
    mode: 'no-jd',
    miner_telemetry_cidr: '',
    pool: {
      name: 'Configuration Smoke Test',
      address: '127.0.0.1',
      port: TEST_POOL_PORT,
      authority_public_key: JDC_AUTHORITY_PUBLIC_KEY,
      user_identity: 'smoke-test.worker',
    },
    fallbackPools: [],
    bitcoin: null,
    jdc: null,
    translator: {
      enable_vardiff: true,
      aggregate_channels: false,
      min_hashrate: 100_000_000_000_000,
      shares_per_minute: 6,
      downstream_extranonce2_size: 4,
    },
  };
}

async function main(): Promise<void> {
  const configDir = await mkdtemp(path.join(os.tmpdir(), 'sv2-ui-image-config-'));

  try {
    for (const image of new Set([
      SV2_APP_IMAGES.translatorNoJd,
      SV2_APP_IMAGES.jd.translator,
      SV2_APP_IMAGES.jd.jdc,
    ])) {
      await pullImage(image);
    }

    const malformedConfigPath = path.join(configDir, 'malformed.toml');
    await writeFile(malformedConfigPath, MALFORMED_CONFIG);

    const noJdPrepared = prepareServiceConfig(baseSetup());
    if (noJdPrepared.kind !== 'ready') throw new Error('Could not prepare no-JD smoke-test configuration');
    const noJdTranslatorConfig = noJdPrepared.files.find((file) => file.filename === 'translator.toml');
    if (!noJdTranslatorConfig) throw new Error('No no-JD Translator configuration was generated');
    const noJdTranslatorPath = path.join(configDir, `no-jd-${noJdTranslatorConfig.filename}`);
    await writeFile(noJdTranslatorPath, noJdTranslatorConfig.contents);

    await assertConfigErrorsAreRecognized(
      'no-JD Translator config',
      SV2_APP_IMAGES.translatorNoJd,
      malformedConfigPath,
      '/config/translator.toml',
      '/app/translator_sv2',
    );

    await checkGeneratedConfig(
      'no-JD Translator config',
      SV2_APP_IMAGES.translatorNoJd,
      noJdTranslatorPath,
      '/config/translator.toml',
      '/app/translator_sv2',
    );

    const jdData: SetupData = {
      ...baseSetup(),
      mode: 'jd',
      bitcoin: {
        core_version: '30',
        network: 'mainnet',
        os: 'linux',
        customDataDir: '',
        socket_path: '/root/.bitcoin/node.sock',
      },
      jdc: {
        jdc_signature: 'smoke-test',
        coinbase_reward_address: '1BoatSLRHtKNngkdXEeobR76b53LETtpyT',
      },
    };
    const jdPrepared = prepareServiceConfig(jdData);
    if (jdPrepared.kind !== 'ready') throw new Error('Could not prepare JD smoke-test configuration');
    const jdTranslatorConfig = jdPrepared.files.find((file) => file.filename === 'translator.toml');
    if (!jdTranslatorConfig) throw new Error('No JD Translator configuration was generated');
    const jdcConfig = jdPrepared.files.find((file) => file.filename === 'jdc.toml');
    if (!jdcConfig) throw new Error('No JDC configuration was generated');

    const jdTranslatorPath = path.join(configDir, `jd-${jdTranslatorConfig.filename}`);
    const jdcPath = path.join(configDir, jdcConfig.filename);
    await writeFile(jdTranslatorPath, jdTranslatorConfig.contents);
    await writeFile(jdcPath, jdcConfig.contents);

    await assertConfigErrorsAreRecognized(
      'JD Translator config',
      SV2_APP_IMAGES.jd.translator,
      malformedConfigPath,
      '/config/translator.toml',
      '/app/translator_sv2',
    );

    await checkGeneratedConfig(
      'JD Translator config',
      SV2_APP_IMAGES.jd.translator,
      jdTranslatorPath,
      '/config/translator.toml',
      '/app/translator_sv2',
    );

    await assertConfigErrorsAreRecognized(
      'JDC config',
      SV2_APP_IMAGES.jd.jdc,
      malformedConfigPath,
      '/config/jdc.toml',
      '/app/jd_client_sv2',
    );

    await checkGeneratedConfig(
      'JDC config',
      SV2_APP_IMAGES.jd.jdc,
      jdcPath,
      '/config/jdc.toml',
      '/app/jd_client_sv2',
    );
  } finally {
    await rm(configDir, { recursive: true, force: true });
  }
}

void main().catch((error) => {
  console.error('sv2-app config compatibility check failed:', error);
  process.exitCode = 1;
});
